
export const products = [
  {
    title: 'Syltherine',
    image: '/src/images/home/Syltherine.png',
    description: 'Stylish cafe chair',
    price: 2500000,
    originalPrice: 3500000,
    badge: '-30%',
  },
  {
    title: 'Leviosa',
    image: '/src/images/home/Leviosa.png',
    description: 'Stylish cafe chair',
    price: 2500000,
    originalPrice: null,
    badge: null,
  },
  {
    title: 'Lolito',
    image: '/src/images/home/Lolito.png',
    description: 'Luxury big sofa',
    price: 7000000,
    originalPrice: 14000000,
    badge: '-50%',
  },
  {
    title: 'Respira',
    image: '/src/images/home/Respira.png',
    description: 'Outdoor bar table and stool',
    price: 500000,
    originalPrice: null,
    badge: 'New',
    badgeColor: 'bg-success-2',
  },
  {
    title: 'Grifo',
    image: '/src/images/home/Grifo.png',
    description: 'Night lamp',
    price: 1500000,
    originalPrice: null,
    badge: null,
  },
  {
    title: 'Muggo',
    image: '/src/images/home/Muggo.png',
    description: 'Small mug',
    price: 150000,
    originalPrice: null,
    badge: 'New',
    badgeColor: 'bg-success-2',
  },
  {
    title: 'Pingky',
    image: '/src/images/home/Pingky.png',
    description: 'Cute bed set',
    price: 7000000,
    originalPrice: 14000000,
    badge: '-50%',
  },
  {
    title: 'Potty',
    image: '/src/images/home/Potty.png',
    description: 'Minimalist flower pot',
    price: 500000,
    originalPrice: null,
    badge: 'New',
    badgeColor: 'bg-success-2',
  },
]
