/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/adminshop': RouteRecordInfo<'/admin/adminshop', '/admin/adminshop', Record<never, never>, Record<never, never>>,
    '/admin/adminuser': RouteRecordInfo<'/admin/adminuser', '/admin/adminuser', Record<never, never>, Record<never, never>>,
    '/admin/createProduct': RouteRecordInfo<'/admin/createProduct', '/admin/createProduct', Record<never, never>, Record<never, never>>,
    '/admin/edit/[id]': RouteRecordInfo<'/admin/edit/[id]', '/admin/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/cart': RouteRecordInfo<'/cart', '/cart', Record<never, never>, Record<never, never>>,
    '/detail_product': RouteRecordInfo<'/detail_product', '/detail_product', Record<never, never>, Record<never, never>>,
    '/product_detail/[id]': RouteRecordInfo<'/product_detail/[id]', '/product_detail/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/shop': RouteRecordInfo<'/shop', '/shop', Record<never, never>, Record<never, never>>,
  }
}
